firebase.initializeApp(FIREBASE_CONFIG);
const auth = firebase.auth(); const db = firebase.firestore(); const storage = firebase.storage();
async function adminSignIn(){ const email=document.getElementById('adminEmail').value; const pass=document.getElementById('adminPass').value; try{ await auth.signInWithEmailAndPassword(email,pass); const user=auth.currentUser; const q=await db.collection('admins').doc(user.uid).get(); if(!q.exists){ alert('Not an admin'); return; } document.getElementById('adminLogin').style.display='none'; document.getElementById('adminPanel').classList.remove('hidden'); loadAdminData(); }catch(e){ alert(e.message); } }
function logout(){ auth.signOut(); location.href='/index.html'; }
function showTab(id){ document.querySelectorAll('.tabpane').forEach(el=>el.classList.add('hidden')); document.getElementById(id).classList.remove('hidden'); }
async function loadAdminData(){ const subs = await db.collection('subscribers').orderBy('created_at','desc').get(); const list=document.getElementById('subscriberList'); list.innerHTML=''; subs.forEach(s=>{ const li=document.createElement('li'); li.textContent=s.data().email; list.appendChild(li); }); const members = await db.collection('users').get(); const mlist=document.getElementById('memberList'); mlist.innerHTML=''; members.forEach(m=>{ const li=document.createElement('li'); li.textContent = m.data().email || m.id; const btn=document.createElement('button'); btn.textContent='Ban'; btn.onclick=async ()=>{ await db.collection('users').doc(m.id).update({banned:true}); alert('Banned'); }; mlist.appendChild(li); mlist.appendChild(btn); }); const sdoc=await db.collection('settings').doc('site').get(); if(sdoc.exists){ const s=sdoc.data(); document.getElementById('adminTitle').value=s.title||''; document.getElementById('adminTag').value=s.tagline||''; document.getElementById('adminPaypal').value=s.paypalClientId||''; document.getElementById('adminPlanId').value=s.paypalPlanId||''; document.getElementById('adminCash').value=s.cashTag||''; } }
async function adminCreatePost(){ const title=document.getElementById('adminPostTitle').value; const body=document.getElementById('adminPostBody').value; const file=document.getElementById('adminPostImage').files[0]; let imageUrl=''; if(file){ const path='admin/'+Date.now()+'-'+file.name; const snap=await storage.ref(path).put(file); imageUrl=await snap.ref.getDownloadURL(); } await db.collection('posts').add({title,content:body,imageUrl,authorName:'admin',created_at: firebase.firestore.FieldValue.serverTimestamp()}); alert('Published'); loadAdminData(); }
async function exportSubscribers(){ const subs=await db.collection('subscribers').get(); let csv='email,created_at\n'; subs.forEach(s=>{ const d=s.data(); csv += '"'+(d.email||'')+'","'+(d.created_at?d.created_at.toDate().toISOString():'')+'"\n'; }); const blob=new Blob([csv],{type:'text/csv'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='subscribers.csv'; a.click(); URL.revokeObjectURL(url); }
async function saveDonationSettings(){ const paypalClientId=document.getElementById('adminPaypal').value; const planId=document.getElementById('adminPlanId').value; const cashTag=document.getElementById('adminCash').value; await db.collection('settings').doc('site').set({paypalClientId:paypalClientId,paypalPlanId:planId,cashTag:cashTag},{merge:true}); alert('Saved'); }
async function saveSiteSettings(){ const title=document.getElementById('adminTitle').value; const tag=document.getElementById('adminTag').value; const file=document.getElementById('adminLogo').files[0]; if(file){ const path='site/'+Date.now()+'-'+file.name; const snap = await storage.ref(path).put(file); const url = await snap.ref.getDownloadURL(); await db.collection('settings').doc('site').set({logo:url},{merge:true}); document.getElementById('logo').src = url; } await db.collection('settings').doc('site').set({title,tagline:tag},{merge:true}); alert('Saved'); loadAdminData(); }
